### ISSUE TITLE
Darwinia 2.0 🚀

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-2.0#9]
- Code
  - [x] `#[deny(missing_docs)]` @darwinia-network/runtime-developers 
- Core
  - [x] #1 @HackFisher 
  - [x] #15 
  - [x] Change token decimal from 9 to 18 @AurevoirXavier 
- Darwinia2 code
  - [x] #27 @AurevoirXavier @jiguantong 
- Runtime
  - [x] #8 @AurevoirXavier 
  - [x] #11 @boundless-forest 
  - [x] #24 #68 @AurevoirXavier @HackFisher 
  - [x] #25 @AurevoirXavier 
  - [x] #30 @AurevoirXavier @boundless-forest 
  - [x] #55 @AurevoirXavier 
  - [x] Add democracy and remove remote-governance #60 @AurevoirXavier 
  - [x] Runtime benchmarks @AurevoirXavier 
  - [x] #26 @AurevoirXavier @boundless-forest 
- Upgrade `darwinia*` pallets to `polkadot-v0.9.36`(latest)
  - [x] pallet-fee-market @boundless-forest  
- Upgrade to latest Substrate version
  - [x] paritytech/substrate/pull/12586
- State
  - Exporting old state
    - [x] #19
  - Process exported state (each task should contain a unit test) 
    - [x] Merge darwinia-balances and pallet-balances @AurevoirXavier 
      - [x] #8
      - [x] #12
    - [x] #10
    - [x] #14
    - [x] #24
    - [x] #108
- Existing chain
  - [x] https://github.com/darwinia-network/darwinia-parachain/pull/163 @AurevoirXavier @boundless-forest 
  - [x] https://github.com/darwinia-network/darwinia-common/pull/1473 @AurevoirXavier 
  - [x] Close all HRMP channels https://github.com/paritytech/subport/issues/520 #278  @AurevoirXavier 
  - [x] Stop Crab1 @darwinia-network/runtime-developers 
  - [ ] Stop Darwinia1 @darwinia-network/runtime-developers 
- Testnet
  - [x] Pangolin2
  - [x] Pangoro2
- Launching
  - [ ] #106 @AurevoirXavier 
  - [ ] Final benchmarks @AurevoirXavier @boundless-forest @jiguantong 
  - [ ] Fund genesis collators in Darwinia1 @AurevoirXavier @hackfisher
  - [ ] #97 @darwinia-network/runtime-developers 
  - [ ] #298 @darwinia-network/runtime-developers  
  - [x] Push the code to [darwinia-network/darwinia](https://github.com/darwinia-network/darwinia) @AurevoirXavier
  - [ ] Check the para id in genesis storage before upgrade, the para id should be same with the 1.0 production parachain
